# Define the service account for the entire build
serviceAccount: 'projects/gke-demo-467801/serviceAccounts/gke-demo@gke-demo-467801.iam.gserviceaccount.com'

# Define the steps of the CI/CD pipeline
steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/nginx-app:$TAG_NAME' # Tag image with Cloud Build's tag/commit SHA
  - '.'

# 2. Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/nginx-app:$TAG_NAME'

# 3. Deploy to GKE using gke-deploy (Recommended)
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - 'run'
  - '--filename=deployment.yaml'
  - '--location=${_GKE_ZONE}'
  - '--cluster=${_GKE_CLUSTER_NAME}'
  # Substitute the image placeholder in the manifest with the actual image path
  - '--image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/nginx-app:$TAG_NAME'

# Options for the entire build
options:
  # Specify the log bucket for build logs
  logging: CLOUD_LOGGING_ONLY

# User-defined substitution variables for flexibility
substitutions:
  _LOCATION: us-east4
  _AR_REPO_NAME: gke-demo
  _GKE_ZONE: us-central1
  _GKE_CLUSTER_NAME: gke-demo-cluster-tbd